# Generated by Django 5.2.17 on 2026-09-13 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preview', models.CharField(default='/static/img/example.png')),
                ('title', models.CharField(default='Coming soon', max_length=255)),
                ('description', models.TextField(default='Coming very soon')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='org',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
