# Generated by Django 5.2.17 on 2026-09-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_skill_experience_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.CharField(default='/static/img/example.png', max_length=255),
        ),
    ]
