# Generated by Django 5.2.17 on 2026-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='preview',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
